services:
  app:
    image: registry.cn-hangzhou.aliyuncs.com/clansty/aquadx-minato:latest
    ports:
      - "83:83"
    volumes:
      - ./config/application.properties:/app/config/application.properties:ro
      - ./data:/app/data

